baseurl = "https://brb3.org/"
languageCode = "en-us"
title = "brb3"
theme = "brb3"
googleAnalytics = "UA-31681523-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
copyright = "© [Bobby Burden III](https://brb3.org)"
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params.theme]
palette = "custom"

[params.about]
title = "brb3.org"
description = "I make stuff for fun sometimes, and write blog posts very infrequently. I mostly write C# and sometimes Go."
logo = "images/rocko.png"

[[params.socialLinks]]
    icon = "fa-brands fa-github"
    title = "github"
    url = "https://github.com/brb3"

[[params.socialLinks]]
    icon = "fa-solid fa-link"
    title = "devanooga"
    url = "https://www.devanooga.com/"

[[params.socialLinks]]
    icon = "fa-solid fa-rss"
    title = "rss"
    url = "/index.xml"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    lineNos = true
    style = 'borland'